apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{ include "listmonk.labels" . | nindent 4 }}
data:
  config.toml: |
    [app]
    address = "0.0.0.0:80"

    [db]
    {{- if .Values.postgres.enabled }}
    host = "{{ include "listmonk.fullname" .}}-postgres"
    {{- else }}
    host = "{{ .Values.postgres.hostname }}"
    {{- end }}
    port = 5432
    database = "{{ .Values.postgres.database }}"
    ssl_mode = "{{ .Values.postgres.ssl_mode }}"
    max_open = 25
    max_idle = 25
    max_lifetime = "300s"
