apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{ include "listmonk.labels" . | nindent 4 }}
data:
  config.toml: |
    [app]
    address = "0.0.0.0:80"

    [db]
    host = "{{ template "listmonk.postgresql.host" . }}"
    port = 5432
    database = "{{ .Values.postgresql.auth.database }}"
    ssl_mode = "disable"
    max_open = 25
    max_idle = 25
    max_lifetime = "300s"
