apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{ include "listmonk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.listmonk.replicas}}
  selector:
    matchLabels:
      deployment: listmonk
      {{ include "listmonk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: listmonk
        {{ include "listmonk.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: LISTMONK_db__user
          value: {{ .Values.postgresql.postgresqlUser }}
        - name: LISTMONK_db__password
          valueFrom:
            secretKeyRef:
            {{- if .Values.postgresql.existingSecret }}
              name: {{ .Values.postgresql.existingSecret }}
            {{- else }}
              name: {{ template "listmonk.postgresql.secret" . }}
            {{- end }}
              key: {{ template "listmonk.postgresql.secretKey" . }}
        image: {{ .Values.listmonk.image.repository }}:{{ .Values.listmonk.image.tag | default .Chart.AppVersion }}
        name: listmonk
        volumeMounts:
        - mountPath: /listmonk/config.toml
          name: config
          subPath: config.toml
      initContainers:
      - env:
        - name: LISTMONK_db__user
          value: {{ .Values.postgresql.postgresqlUser }}
        - name: LISTMONK_db__password
          valueFrom:
            secretKeyRef:
            {{- if .Values.postgresql.existingSecret }}
              name: {{ .Values.postgresql.existingSecret }}
            {{- else }}
              name: {{ template "listmonk.postgresql.secret" . }}
            {{- end }}
              key: {{ template "listmonk.postgresql.secretKey" . }}
        name: init
        image: {{ .Values.listmonk.image.repository }}:{{ .Values.listmonk.image.tag | default .Chart.AppVersion }}
        command:
        - sh
        - -c
        - "./listmonk --install --idempotent --yes && ./listmonk --upgrade --yes"
        volumeMounts:
        - mountPath: /listmonk/config.toml
          name: config
          subPath: config.toml
      volumes:
      - configMap:
          name: {{ include "listmonk.fullname" . }}-listmonk
        name: config
