{{- if .Values.postgres.enable }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
  name: {{ include "listmonk.fullname" . }}-postgres
data:
  PASSWORD: {{ required "A valid .Values.postgres.password is required" .Values.postgres.password | b64enc }}
  USER: {{ required "A valid .Values.postgres.user is required" .Values.postgres.user | b64enc }}
{{- end }}