{{- if .Values.postgres.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "listmonk.fullname" . }}-postgres
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    statefulSet: postgres
      {{- include "listmonk.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
{{- end }}