apiVersion: v1
kind: Service
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{ include "listmonk.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    deployment: listmonk
    {{ include "listmonk.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
